/* Shared by index.html (the app) and review.html (clinical review page). Edit conditions here. */
// [pattern, medical term, everyday name, ICD-10-CM code (category level), group]. Order matters: specific terms come before general ones,
// and each match is blanked out so "psoriatic arthritis" isn't also counted as "psoriasis".
const CONDITIONS = [
  // Heart and blood vessels
  // MACE is one composite indication; blank its "(CV death, non-fatal MI, or non-fatal stroke)" list so it isn't split up.
  [/major adverse cardiovascular (?:\(CV\) )?events(?: \((?:[^()]|\([^()]*\))*\))?|\bMACE\b/i, "Major adverse cardiovascular events (MACE) risk reduction", "Lower risk of heart attack, stroke or heart-related death", "", "Heart and blood vessels"],
  [/pulmonary arterial hypertension|\bPAH\b/i, "Pulmonary arterial hypertension", "High blood pressure in the lungs", "I27.0", "Heart and blood vessels"],
  [/ocular hypertension/i, "Ocular hypertension", "High eye pressure", "H40.05", "Heart and blood vessels"],
  [/(?<!portal |intracranial )hypertension|high blood pressure/i, "Hypertension", "High blood pressure", "I10", "Heart and blood vessels"],
  [/hypertriglyceridemia|elevated triglycerides/i, "Hypertriglyceridemia", "High triglycerides", "E78.1", "Heart and blood vessels"],
  [/hyperlipidemia|dyslipidemia|hypercholesterolemia|\bLDL-C\b|low-density lipoprotein/i, "Hyperlipidemia", "High cholesterol", "E78.5", "Heart and blood vessels"],
  [/myocardial infarction|\bMI\b/, "Myocardial infarction", "Heart attack", "I21", "Heart and blood vessels"],
  [/heart failure/i, "Heart failure", "Weak heart / heart failure", "I50", "Heart and blood vessels"],
  [/atrial fibrillation/i, "Atrial fibrillation", "Irregular heartbeat (AFib)", "I48", "Heart and blood vessels"],
  [/ventricular (tachy)?arrhythmia|ventricular tachycardia/i, "Ventricular arrhythmia", "Dangerous fast heart rhythm", "I47.2", "Heart and blood vessels"],
  [/angina/i, "Angina", "Chest pain from heart disease", "I20", "Heart and blood vessels"],
  [/coronary (heart|artery) disease|\bCHD\b|\bCAD\b/, "Coronary heart disease", "Clogged heart arteries", "I25.10", "Heart and blood vessels"],
  [/peripheral arter(y|ial) disease/i, "Peripheral artery disease", "Poor circulation in the legs", "I73.9", "Heart and blood vessels"],
  [/deep vein thrombosis|\bDVT\b/, "Deep vein thrombosis", "Blood clots in the legs", "I82.4", "Heart and blood vessels"],
  [/pulmonary embolism/i, "Pulmonary embolism", "Blood clot in the lungs", "I26", "Heart and blood vessels"],
  [/stroke/i, "Stroke", "Stroke", "I63", "Heart and blood vessels"],
  [/\bedema\b/i, "Edema", "Fluid build-up / swelling", "R60", "Heart and blood vessels"],
  // Hormones and metabolism
  [/diabetic (nephropathy|kidney disease)([^.]{0,120}type 2 diabetes)?/i, "Diabetic nephropathy", "Kidney damage from diabetes", "E11.21", "Hormones and metabolism"],
  [/type 2 diabetes|diabetes mellitus type 2|non-insulin[- ]dependent/i, "Type 2 diabetes mellitus", "Type 2 diabetes (high blood sugar)", "E11", "Hormones and metabolism"],
  [/type 1 diabetes/i, "Type 1 diabetes mellitus", "Type 1 diabetes", "E10", "Hormones and metabolism"],
  [/chronic weight management|obesity|overweight|weight reduction|weight loss|excess body weight/i, "Obesity", "Weight loss", "E66", "Hormones and metabolism"],
  [/hypothyroidism/i, "Hypothyroidism", "Underactive thyroid", "E03.9", "Hormones and metabolism"],
  [/hyperthyroidism|graves/i, "Hyperthyroidism", "Overactive thyroid", "E05", "Hormones and metabolism"],
  [/osteoporosis/i, "Osteoporosis", "Thinning, brittle bones", "M81", "Hormones and metabolism"],
  [/\bgout\b|hyperuricemia/i, "Gout", "Gout (painful joint flare-ups)", "M10", "Hormones and metabolism"],
  [/hypogonadism|testosterone deficiency/i, "Hypogonadism", "Low testosterone", "E29.1", "Hormones and metabolism"],
  [/vasomotor symptoms|menopaus/i, "Vasomotor symptoms of menopause", "Menopause hot flashes", "N95.1", "Hormones and metabolism"],
  [/contracepti|prevention of pregnancy|prevent pregnancy/i, "Contraception", "Birth control", "Z30", "Hormones and metabolism"],
  // Lungs and allergy
  [/chronic obstructive pulmonary disease|\bCOPD\b|emphysema|chronic bronchitis/i, "COPD", "COPD / emphysema", "J44", "Lungs and allergy"],
  [/asthma|bronchospasm/i, "Asthma", "Asthma / wheezing", "J45", "Lungs and allergy"],
  [/obstructive sleep apnea|\bOSA\b/i, "Obstructive sleep apnea", "Sleep apnea (breathing stops during sleep)", "G47.33", "Lungs and allergy"],
  [/allergic rhinitis|hay fever|upper respiratory allerg/i, "Allergic rhinitis", "Hay fever / seasonal allergies", "J30", "Lungs and allergy"],
  [/urticaria|\bhives\b/i, "Urticaria", "Hives", "L50", "Lungs and allergy"],
  [/anaphyla/i, "Anaphylaxis", "Severe allergic reaction", "T78.2", "Lungs and allergy"],
  [/nasal congestion|stuffy nose/i, "Nasal congestion", "Stuffy nose", "R09.81", "Lungs and allergy"],
  [/\bcough/i, "Cough", "Cough", "R05", "Lungs and allergy"],
  [/common cold/i, "Common cold", "Common cold", "J00", "Lungs and allergy"],
  [/sore throat/i, "Pharyngitis", "Sore throat", "J02.9", "Lungs and allergy"],
  // Stomach and gut
  [/gastroesophageal reflux|\bGERD\b|heartburn|acid indigestion/i, "Gastroesophageal reflux disease", "Acid reflux / heartburn", "K21", "Stomach and gut"],
  [/erosive esophagitis/i, "Erosive esophagitis", "Acid damage to the food pipe", "K21.0", "Stomach and gut"],
  [/(duodenal|gastric|peptic) ulcer/i, "Peptic ulcer disease", "Stomach ulcers", "K25–K27", "Stomach and gut"],
  [/helicobacter pylori|H\. pylori/i, "Helicobacter pylori infection", "H. pylori stomach infection", "B96.81", "Stomach and gut"],
  [/ulcerative colitis/i, "Ulcerative colitis", "Ulcerative colitis (bowel inflammation)", "K51", "Stomach and gut"],
  [/crohn/i, "Crohn’s disease", "Crohn’s disease (bowel inflammation)", "K50", "Stomach and gut"],
  [/irritable bowel/i, "Irritable bowel syndrome", "IBS", "K58", "Stomach and gut"],
  [/constipation/i, "Constipation", "Constipation", "K59.0", "Stomach and gut"],
  [/diarrh/i, "Diarrhea", "Diarrhea", "R19.7", "Stomach and gut"],
  [/nausea|vomiting/i, "Nausea and vomiting", "Nausea / throwing up", "R11", "Stomach and gut"],
  [/motion sickness/i, "Motion sickness", "Motion sickness", "T75.3", "Stomach and gut"],
  // Brain and mental health
  [/major depressive disorder|\bMDD\b|depression/i, "Major depressive disorder", "Depression", "F32–F33", "Brain and mental health"],
  [/generalized anxiety disorder|\bGAD\b/, "Generalized anxiety disorder", "Anxiety", "F41.1", "Brain and mental health"],
  [/social anxiety disorder/i, "Social anxiety disorder", "Social anxiety", "F40.10", "Brain and mental health"],
  [/panic disorder/i, "Panic disorder", "Panic attacks", "F41.0", "Brain and mental health"],
  [/obsessive[- ]compulsive|\bOCD\b/i, "Obsessive-compulsive disorder", "OCD", "F42", "Brain and mental health"],
  [/post-?traumatic stress|\bPTSD\b/i, "Post-traumatic stress disorder", "PTSD", "F43.1", "Brain and mental health"],
  [/premenstrual dysphoric|\bPMDD\b/i, "Premenstrual dysphoric disorder", "Severe PMS", "F32.81", "Brain and mental health"],
  [/anxiety/i, "Anxiety disorders", "Anxiety", "F41.9", "Brain and mental health"],
  [/bipolar|manic episodes|mania/i, "Bipolar I disorder", "Bipolar disorder", "F31", "Brain and mental health"],
  [/schizophrenia/i, "Schizophrenia", "Schizophrenia", "F20", "Brain and mental health"],
  [/attention[- ]deficit|\bADHD\b/i, "Attention deficit hyperactivity disorder", "ADHD", "F90", "Brain and mental health"],
  [/insomnia/i, "Insomnia", "Trouble sleeping", "G47.0", "Brain and mental health"],
  [/narcolepsy/i, "Narcolepsy", "Excessive daytime sleepiness", "G47.4", "Brain and mental health"],
  [/epilep|seizure/i, "Epilepsy", "Seizures / epilepsy", "G40", "Brain and mental health"],
  [/migraine/i, "Migraine", "Migraine", "G43", "Brain and mental health"],
  [/parkinson/i, "Parkinson’s disease", "Parkinson’s disease", "G20", "Brain and mental health"],
  [/alzheimer|dementia/i, "Alzheimer’s disease", "Alzheimer’s / memory loss", "G30", "Brain and mental health"],
  [/multiple sclerosis/i, "Multiple sclerosis", "MS", "G35", "Brain and mental health"],
  [/neuropathic pain|neuralgia|peripheral neuropathy/i, "Neuropathic pain", "Nerve pain", "M79.2", "Brain and mental health"],
  [/fibromyalgia/i, "Fibromyalgia", "Fibromyalgia (widespread pain)", "M79.7", "Brain and mental health"],
  [/smoking cessation|stop smoking|quit smoking/i, "Smoking cessation", "Quitting smoking", "F17.2", "Brain and mental health"],
  [/opioid (use disorder|dependence|addiction)/i, "Opioid use disorder", "Opioid addiction", "F11.2", "Brain and mental health"],
  [/opioid overdose/i, "Opioid overdose", "Opioid overdose", "T40.2", "Brain and mental health"],
  [/alcohol (dependence|use disorder)/i, "Alcohol use disorder", "Alcohol addiction", "F10.2", "Brain and mental health"],
  // Joints, skin and immune
  [/rheumatoid arthritis/i, "Rheumatoid arthritis", "Rheumatoid arthritis (RA)", "M05–M06", "Joints, skin and immune"],
  [/psoriatic arthritis/i, "Psoriatic arthritis", "Psoriatic arthritis", "L40.5", "Joints, skin and immune"],
  [/juvenile idiopathic arthritis|juvenile arthritis/i, "Polyarticular juvenile idiopathic arthritis", "Juvenile arthritis", "M08", "Joints, skin and immune"],
  [/ankylosing spondylitis|axial spondyloarthritis/i, "Ankylosing spondylitis", "Spine arthritis", "M45", "Joints, skin and immune"],
  [/osteoarthritis/i, "Osteoarthritis", "Wear-and-tear arthritis", "M15–M19", "Joints, skin and immune"],
  [/\barthritis\b/i, "Arthritis", "Arthritis / joint pain", "M19.90", "Joints, skin and immune"],
  [/plaque psoriasis|psoriasis/i, "Plaque psoriasis", "Psoriasis (scaly skin patches)", "L40.0", "Joints, skin and immune"],
  [/hidradenitis suppurativa/i, "Hidradenitis suppurativa", "Painful skin boils", "L73.2", "Joints, skin and immune"],
  [/uveitis/i, "Uveitis", "Eye inflammation", "H20", "Joints, skin and immune"],
  [/atopic dermatitis|eczema/i, "Atopic dermatitis", "Eczema", "L20", "Joints, skin and immune"],
  [/\bacne\b/i, "Acne vulgaris", "Acne", "L70.0", "Joints, skin and immune"],
  [/lupus/i, "Systemic lupus erythematosus", "Lupus", "M32", "Joints, skin and immune"],
  [/(organ|kidney|renal|liver|heart|allograft|transplant) rejection|allogeneic (stem cell )?transplant/i, "Prophylaxis of organ rejection", "Preventing transplant rejection", "T86", "Joints, skin and immune"],
  // Pain and fever
  [/menstrual cramps|dysmenorrhea/i, "Primary dysmenorrhea", "Period cramps", "N94.4", "Pain and fever"],
  [/backache|back pain/i, "Back pain", "Back pain", "M54.9", "Pain and fever"],
  [/toothache|dental pain/i, "Dental pain", "Toothache", "K08.89", "Pain and fever"],
  [/muscular aches|muscle aches|muscle pain/i, "Myalgia", "Muscle aches", "M79.1", "Pain and fever"],
  [/headache/i, "Headache", "Headache", "R51.9", "Pain and fever"],
  [/(mild to moderate|moderate to severe|acute|chronic|minor)( aches and)? pain|relief of pain|management of pain|pain severe enough/i, "Pain", "Pain relief", "R52", "Pain and fever"],
  [/\bfever\b/i, "Fever", "Fever", "R50.9", "Pain and fever"],
  // Infections
  [/\bHIV\b|human immunodeficiency virus/, "HIV-1 infection", "HIV", "B20", "Infections"],
  [/chronic hepatitis B|hepatitis B virus infection|\bHBV infection/i, "Chronic hepatitis B", "Hepatitis B (liver infection)", "B18.1", "Infections"],
  [/chronic hepatitis C|hepatitis C virus infection|\bHCV infection/i, "Chronic hepatitis C", "Hepatitis C (liver infection)", "B18.2", "Infections"],
  [/herpes zoster|shingles/i, "Herpes zoster", "Shingles", "B02", "Infections"],
  [/herpes|cold sores/i, "Herpes simplex", "Herpes / cold sores", "B00", "Infections"],
  [/\binfluenza\b(?! type b)/i, "Influenza", "Flu", "J10–J11", "Infections"],
  [/COVID-19|SARS-CoV-2/i, "COVID-19", "COVID-19", "U07.1", "Infections"],
  [/pneumonia/i, "Pneumonia", "Pneumonia (lung infection)", "J18", "Infections"],
  [/urinary tract infection|cystitis|pyelonephritis/i, "Urinary tract infection", "Bladder / kidney infection (UTI)", "N39.0", "Infections"],
  [/sinusitis/i, "Acute bacterial sinusitis", "Sinus infection", "J01", "Infections"],
  [/otitis media/i, "Otitis media", "Ear infection", "H65–H66", "Infections"],
  [/pharyngitis|tonsillitis/i, "Pharyngitis / tonsillitis", "Strep throat", "J02–J03", "Infections"],
  [/skin (and skin structure|and soft tissue) infection/i, "Skin and skin structure infections", "Skin infections", "L00–L08", "Infections"],
  [/candidiasis|fungal infection|yeast infection|onychomycosis/i, "Fungal infections", "Yeast / fungal infections", "B35–B37", "Infections"],
  [/bacterial infection|infections caused by (susceptible|designated)/i, "Bacterial infections", "Bacterial infections", "A49.9", "Infections"],
  // Cancer and blood
  [/hepatocellular carcinoma|\bHCC\b/i, "Hepatocellular carcinoma", "Liver cancer", "C22.0", "Cancer and blood"],
  [/non-small cell lung cancer|\bNSCLC\b|small cell lung cancer|\bSCLC\b/i, "Lung cancer (NSCLC / SCLC)", "Lung cancer", "C34", "Cancer and blood"],
  [/head and neck/i, "Head and neck squamous cell carcinoma", "Head and neck cancer", "C00–C14, C32", "Cancer and blood"],
  [/renal cell carcinoma|\bRCC\b/i, "Renal cell carcinoma", "Kidney cancer", "C64", "Cancer and blood"],
  [/urothelial|bladder cancer/i, "Urothelial carcinoma", "Bladder cancer", "C67", "Cancer and blood"],
  [/cervical cancer/i, "Cervical cancer", "Cervical cancer", "C53", "Cancer and blood"],
  [/endometrial/i, "Endometrial carcinoma", "Uterine cancer", "C54.1", "Cancer and blood"],
  [/ovarian cancer/i, "Ovarian cancer", "Ovarian cancer", "C56", "Cancer and blood"],
  [/gastric (or gastroesophageal junction )?(cancer|adenocarcinoma)|stomach cancer/i, "Gastric cancer", "Stomach cancer", "C16", "Cancer and blood"],
  [/esophageal (cancer|carcinoma)/i, "Esophageal cancer", "Esophagus cancer", "C15", "Cancer and blood"],
  [/pancreatic (cancer|adenocarcinoma)/i, "Pancreatic cancer", "Pancreatic cancer", "C25", "Cancer and blood"],
  [/thyroid cancer|thyroid carcinoma/i, "Thyroid cancer", "Thyroid cancer", "C73", "Cancer and blood"],
  [/mesothelioma/i, "Mesothelioma", "Mesothelioma (lung lining cancer)", "C45", "Cancer and blood"],
  [/merkel cell/i, "Merkel cell carcinoma", "Rare skin cancer (Merkel cell)", "C4A", "Cancer and blood"],
  [/cutaneous squamous cell/i, "Cutaneous squamous cell carcinoma", "Skin cancer (squamous cell)", "C44.92", "Cancer and blood"],
  [/biliary tract|cholangiocarcinoma/i, "Biliary tract cancer", "Bile duct cancer", "C22.1, C24", "Cancer and blood"],
  [/triple-negative/i, "Triple-negative breast cancer", "Breast cancer", "C50", "Cancer and blood"],
  [/breast cancer/i, "Breast cancer", "Breast cancer", "C50", "Cancer and blood"],
  [/prostate cancer/i, "Prostate cancer", "Prostate cancer", "C61", "Cancer and blood"],
  [/colorectal cancer|colon cancer/i, "Colorectal cancer", "Colon cancer", "C18–C20", "Cancer and blood"],
  [/leukemia/i, "Leukemia", "Blood cancer (leukemia)", "C91–C95", "Cancer and blood"],
  [/lymphoma/i, "Lymphoma", "Lymph node cancer (lymphoma)", "C81–C88", "Cancer and blood"],
  [/multiple myeloma/i, "Multiple myeloma", "Bone marrow cancer (myeloma)", "C90.0", "Cancer and blood"],
  [/melanoma/i, "Melanoma", "Skin cancer (melanoma)", "C43", "Cancer and blood"],
  [/anemia/i, "Anemia", "Low red blood cells (anemia)", "D64.9", "Cancer and blood"],
  // Other
  [/erectile dysfunction/i, "Erectile dysfunction", "Erectile dysfunction (ED)", "N52", "Other"],
  [/benign prostatic hyperplasia|\bBPH\b/i, "Benign prostatic hyperplasia", "Enlarged prostate", "N40", "Other"],
  [/overactive bladder|urinary incontinence/i, "Overactive bladder", "Overactive bladder / leaking urine", "N32.81", "Other"],
  [/glaucoma/i, "Glaucoma", "Glaucoma", "H40", "Other"],
  [/macular degeneration/i, "Macular degeneration", "Age-related vision loss", "H35.3", "Other"],
  [/chronic kidney disease/i, "Chronic kidney disease", "Kidney disease", "N18", "Other"],
];
